apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/albertollamaso/kafka-poc-environment.git
    targetRevision: main
    path: helm-charts/kafka
  destination:
    name: in-cluster
    namespace: applications
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true